version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /project/node_modules
      - .:/project
      
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /project/node_modules
      - .:/project
    command: ["npm", "run", "test"]


